### your site title here

title: "A Hacker Next Door"

description: "신입 모의해커의 블로그 입니다."

#permalink: /:title

baseurl: /

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md

#pagenate
plugins:
  -jekyll-paginate # 플러그인 사용을 의미한다. (Jekyll 3)
#pagination settings
pagenate: 2 # 한 페이지당 보여줄 posts 수
# :num은 페이지마다 번호를 각각 부여한다.
pagenate_path: "/posts/page/:num" #다음 페이지에 해당하는 URL


# Tracker
analytics: 

# Comments
disqus-shortname: webjeda-demo

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
